In [1]:
import numpy as np

In [2]:
bmat = np.array([[2,0,0,0],
                 [0,0,1,0],
                 [0,0,1,0],
                 [0,0,0,0],
                 [0,1,0,0],
                 [1,0,0,1],
                 [0,0,0,0],
                 [0,0,1,0],
                 [0,1,0,0],
                 [0,0,0,0],
                 [1,0,0,1],
                 [0,0,1,0],
                 [0,0,0,0],
                 [0,1,0,0],
                 [0,1,0,0],
                 [0,0,0,2]])

In [19]:
# H2

# The 4 most important determinants:

   #  *   1    0.993647  (    0,    0)  1AX 
   #  *   2   -0.112544  (    1,    1)  2AX 


   # ==> DETCI root 1 information <==

   #  DETCI Root 1 energy =    -0.530773357428456

   # The 4 most important determinants:

   #  *   1    0.707107  (    0,    1)  1AA 2AB 
   #  *   2   -0.707107  (    1,    0)  1AB 2AA 


   # ==> DETCI root 2 information <==

   #  DETCI Root 2 energy =    -0.168352433358942

   # The 4 most important determinants:

   #  *   1    0.707107  (    1,    0)  1AB 2AA 
   #  *   2    0.707107  (    0,    1)  1AA 2AB 


   # ==> DETCI root 3 information <==

   #  DETCI Root 3 energy =     0.483142672291850

   # The 4 most important determinants:

   #  *   1    0.993647  (    1,    1)  2AX 
   #  *   2    0.112544  (    0,    0)  1AX 


ci1 = np.array([0.993647,0,0, -0.112544])
ci2 = np.array([0,0.707107,-0.707107,0])
ci3 = np.array([0,0.707107,0.707107,0])
ci4 = np.array([0.112544,0,0,0.993647])

# HeH+

   # ==> DETCI root 0 information <==

   #  DETCI Root 0 energy =    -2.851024030048660

   # The 4 most important determinants:

   #  *   1    0.997658  (    0,    0)  1AX 
   #  *   2   -0.066047  (    1,    1)  2AX 
   #  *   3    0.012560  (    0,    1)  1AA 2AB 
   #  *   4    0.012560  (    1,    0)  1AB 2AA 


   # ==> DETCI root 1 information <==

   #  DETCI Root 1 energy =    -2.038741247458640

   # The 4 most important determinants:

   #  *   1   -0.707107  (    0,    1)  1AA 2AB 
   #  *   2    0.707107  (    1,    0)  1AB 2AA 


   # ==> DETCI root 2 information <==

   #  DETCI Root 2 energy =    -1.817019498247150

   # The 4 most important determinants:

   #  *   1   -0.688092  (    1,    0)  1AB 2AA 
   #  *   2   -0.688092  (    0,    1)  1AA 2AB 
   #  *   3    0.228052  (    1,    1)  2AX 
   #  *   4    0.032423  (    0,    0)  1AX 


   # ==> DETCI root 3 information <==

   #  DETCI Root 3 energy =    -0.492134556478119

   # The 4 most important determinants:

   #  *   1    0.971406  (    1,    1)  2AX 
   #  *   2    0.162394  (    1,    0)  1AB 2AA 
   #  *   3    0.162394  (    0,    1)  1AA 2AB 
   #  *   4    0.060221  (    0,    0)  1AX 
# 


# ci1 = np.array([0.997658,0.012560,0.012560,-0.066047])
# ci2 = np.array([0,0.707107,-0.707107,0])
# ci3 = np.array([0.032423,-0.688092,-0.688092,0.228052])
# ci4 = np.array([0.060221,0.162394,0.162394,0.971406])

In [20]:
cimat = np.stack([ci1,ci2,ci3,ci4],axis=1)

In [21]:
cimat.shape

(4, 4)

In [22]:
bmat.shape

(16, 4)

In [23]:
# (bmat @ cimat)[0].reshape((2,2))

In [24]:
bmat2 = np.copy(bmat)
bmat2[:,2] = bmat[:,1]
bmat2[:,1] = bmat[:,2]
bten = bmat2.reshape((4,4,2,2))

In [25]:
bten2 = np.einsum('kq,qpbc,pl->klbc',cimat.T,bten,cimat)

In [26]:
print(bten2.reshape((16,4)))

[[ 1.97466872  0.          0.          0.0253323 ]
 [ 0.          0.          0.          0.        ]
 [ 0.          1.4052295  -0.1591613   0.        ]
 [ 0.22365802  0.          0.         -0.22365802]
 [ 0.          0.          0.          0.        ]
 [ 1.00000062  0.          0.          1.00000062]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.         -0.1591613   1.4052295   0.        ]
 [ 0.          0.          0.          0.        ]
 [ 1.00000062  0.          0.          1.00000062]
 [ 0.          1.4052295   0.1591613   0.        ]
 [ 0.22365802  0.          0.         -0.22365802]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.1591613   1.4052295   0.        ]
 [ 0.0253323   0.          0.          1.97466872]]


In [ ]:
# psi4 result
# heh+

[[ 1.99095998  0.02340198  0.02340198  0.00904002]
 [ 0.          0.          0.          0.        ]
 [ 0.0474093  -1.36723269  0.09170781 -0.0474093 ]
 [ 0.12423837  0.34842876 -0.01993864 -0.12423837]
 [ 0.          0.          0.          0.        ]
 [ 1.          0.          0.          1.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.0474093   0.09170781 -1.36723269 -0.0474093 ]
 [ 0.          0.          0.          0.        ]
 [ 0.94904348 -0.35846161 -0.35846161  1.05095652]
 [-0.2195787  -1.32630291 -0.00880602  0.2195787 ]
 [ 0.12423837 -0.01993864  0.34842876 -0.12423837]
 [ 0.          0.          0.          0.        ]
 [-0.2195787  -0.00880602 -1.32630291  0.2195787 ]
 [ 0.05999654  0.33505963  0.33505963  1.94000346]]

# h2
# [[1.97466775 0.         0.         0.02533225]
#  [0.         0.         0.         0.        ]
#  [0.         1.40522872 0.         0.        ]
#  [0.22365774 0.         0.         0.        ]
#  [0.         0.         0.         0.        ]
#  [1.00000000 0.         0.         1.00000000]
#  [0.         0.         0.         0.        ]
#  [0.         0.         0.         0.        ]
#  [0.         0.         1.40522872 0.        ]
#  [0.         0.         0.         0.        ]
#  [1.00000000 0.         0.         1.00000000]
#  [0.         1.40522872 0.15916109 0.        ]
#  [0.22365774 0.         0.         0.        ]
#  [0.         0.         0.         0.        ]
#  [0.         0.15916109 1.40522872 0.        ]
#  [0.02533225 0.         0.         1.97466775]]

In [29]:
bten2[0,0]

array([[1.99095848, 0.02340207],
       [0.02340207, 0.00903992]])

In [30]:
bten2[1,0]

array([[0., 0.],
       [0., 0.]])

In [32]:
bten2[1,1]

array([[1.00000062, 0.        ],
       [0.        , 1.00000062]])

In [33]:
bten2[0,2]

array([[ 0.04740926,  0.09170729],
       [-1.36723231, -0.04740917]])

In [34]:
bten2[2,1]

array([[0., 0.],
       [0., 0.]])

In [35]:
bten2[2,2]

array([[ 0.9490437 , -0.35846153],
       [-0.35846153,  1.05095663]])

In [37]:
bten2[0,3]

array([[ 0.12423926, -0.01993852],
       [ 0.34842907, -0.12423757]])

In [38]:
bten2[1,3]

array([[0., 0.],
       [0., 0.]])

In [39]:
bten2[2,3]

array([[-0.21957893, -0.00880662],
       [-1.32630279,  0.21957814]])

In [40]:
bten2[3,3]

array([[0.05999676, 0.33506007],
       [0.33506007, 1.94000286]])